name: 'xbox360-controller-manager'
on:
  push:
    branches:
      - 'master'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout source
        uses: actions/checkout@v2
      - name: setup node 10 environment
        uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: install
        run: npm ci --ignore-scripts
      - name: build
        run: npm run build:production
      - name: unit test
        run: npm run test
      - name: install functions
        run: npm ci --prefix functions --ignore-scripts
      - name: firebase deploy
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting,functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
